<template>
  <div>
    <base-docs-title :title="`How to structure the submission metadata file`">
    </base-docs-title>

    <div class="flex flex-col">
      <base-docs-subtitle> Background </base-docs-subtitle>

      <div class="my-2">
        <p class="font-asap text-black dark:text-white mb-2">
          SODA helps you prepare the
          <span class="span-content print:text-sm print:dark:text-black">
            <router-link
              to="/sodaforsparc/docs/Create-submission-xlsx"
              class="
                hover:underline
                text-blue-600
                dark:text-blue-400
                print:text-sm print:dark:text-black
              "
            >
              <span
                class="
                  font-asap
                  print:text-sm print:text-black print:dark:text-black
                "
              >
                submission metadata file
              </span>
            </router-link>
          </span>
          conveniently. We explain here how it must be structured according to
          the SPARC rules in order to provide some insight about the structure
          of the file generated by SODA.
        </p>
      </div>

      <base-docs-subtitle> How to </base-docs-subtitle>

      <ul class="docs-ul list-outside list-disc">
        <li>
          Format: the submission file is accepted in either xlsx, csv, or json
          format. SODA generates it in the xlsx format based on the template
          provided by the Curation Team. A screenshot is provided below:
        </li>

        <div class="img-parent-div">
          <img
            src="https://github.com/fairdataihub/SODA-for-SPARC/blob/main/docs/documentation/How%20to/submission/submission-template.PNG?raw=true"
          />
        </div>

        <li>
          Location in the dataset: The submission file must be included in the
          high-level dataset folder.
        </li>

        <li>
          Content: The "Submission Item" and "Value" columns are mandatory (the
          "Definition" column could be kept or removed). Each of the three
          "Submission Item" element must be provided a "Value".
        </li>

        <ul class="docs-ul list-outside list-disc">
          <li>SPARC Award number: The number of your SPARC award.</li>

          <li>
            Milestone achieved: This milestone must match exactly with one of
            the milestones agreed with the NIH in the Dataset Deliverables
            document. A screenshot of a sample Dataset Deliverables document is
            provided below. In case the dataset isn't related to a pre-agreed
            dataset, it should be explicitly mentioned (e.g., "Not included in
            the Dataset Deliverables document").
          </li>

          <li>
            Milestone completion date: This date must match exactly with the
            completion date agreed with the NIH in the Dataset Deliverables
            document for the above mentioned "Milestone achieved". In the case
            the dataset isn't related to a pre-agreed milestone, it should be
            explicitly mentioned (e.g., "Not included in the Dataset
            Deliverables document").
          </li>

          <div class="img-parent-div">
            <img
              src="https://github.com/fairdataihub/SODA-for-SPARC/blob/main/docs/documentation/How%20to/submission/data-deliverables-doc-example.PNG?raw=true"
            />
          </div>
        </ul>
      </ul>
    </div>
  </div>
</template>

<script>
export default {
  name: "HowToSubmission",
};
</script>
