name: Create release on GitHub

on:
  push:
    branches:
      - main

jobs:
  release-version-on-github:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install Node.js dependencies
        run: pnpm install --frozen-lockfile

      - name: Format check
        run: pnpm format

      - name: Lint check
        run: pnpm lint

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_ACTIONS }}
        run: pnpm semantic-release
